#!/usr/bin/env bash

PREFIX="bash-brew-service"
EXTENSION="plist"
PLIST_NAME="$1"
PLIST_PATH="$HOME/Library/LaunchAgents/$PREFIX.$PLIST_NAME.$EXTENSION"

# no plist file specified
if [ -z "$PLIST_NAME" ] ; then
  echo "Error: No service name specified"
  exit
fi

# just do it!
if [ -e "$PLIST_PATH" ] ; then
  rm "$PLIST_PATH"
else
  echo "Error: File not found"
fi
